server:
  port: 9000

spring:
  profiles:
    active: minikube
  jpa:
    database: postgresql

    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sleuth:
    enabled: true
    propagation-keys: authorization

  security:
    issure-uri: http://upspoon-authorization-user.com


  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://upspoon-authorization-user-postgresql:5432/postgres
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver

  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true

  liquibase:
    change-log: "classpath:db/changelog/master.xml"
    enabled: true
    contexts: dev



logging:
  level:
    root: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG

client:
  redirect-uri: http://127.0.0.1:5173,https://oidcdebugger.com/debug