apiVersion: v1
data:
  application.yaml: |+
    server:
      port: 80
    
    spring:
      profiles:
        active: aws
      main:
        allow-bean-definition-overriding: true
    
      sleuth:
        enabled: true
        propagation-keys: authorization
    
      security:
        oauth2:
          resourceserver:
            jwt:
              issuer-uri: ${APP_ISSURE_URI}
    
    springdoc:
      swagger-ui:
        path: /swagger-ui.html
        operationSorter: method
        enabled: true
        disable-swagger-default-url: true
    
    logging:
      level:
        root: DEBUG
        org.springframework.web: DEBUG
        org.springframework.security: DEBUG
        org.springframework.security.oauth2: DEBUG
    
    client:
      authorization-api:
        name: authorization-user
        url: ${APP_ISSURE_URI}
      order-api:
        name: order
        url: http://upspoon-order:80
      stock-api:
        name: stock
        url: http://upspoon-stock:80
      organization-api:
        name: organization
        url: http://upspoon-organization:80
      booking-api:
        name: booking
        url: http://upspoon-booking:80
      user-api:
        name: user
        url: http://upspoon-user:80


kind: ConfigMap
metadata:
  labels:
    app: upspoon-gw-configmap
  name: upspoon-gw-configmap-app

---
apiVersion: v1
data:
  APP_ISSURE_URI: http://your-auth-server-url
  SPRING_CLOUD_KUBERNETES_CONFIG_ENABLED: "true"
  SPRING_CLOUD_KUBERNETES_CONFIG_NAME: upspoon-gw-configmap-app
  SPRING_CLOUD_KUBERNETES_SECRET_ENABLED: "true"
  SPRING_CLOUD_BOOTSTRAP_ENABLED: "true"


kind: ConfigMap
metadata:
  labels:
    app: upspoon-gw-configmap
  name: upspoon-gw-configmap-env