# Use postgres/example user/password credentials
version: '3.8'
services:
  postgres-authorization-user:
    restart: always
    image: postgres:13.2
    container_name: postgres-authorization-user

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5431:5431"
    command: -p 5431