server:
  port: 8083


spring:
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5433/postgres
    type: com.zaxxer.hikari.HikariDataSource
  main:
    allow-circular-references: true



logging:
  level:
    org: info

kafka:
  address: 127.0.0.1:9092
  group-id: upspoon-group-id
  topic-organization-create: topic-organization-create
  topic-organization-create-fail: topic-organization-create-fail
  topic-order-create: topic-order-create
  topic-stock-failed: topic-stock-failed
  topic-order-created-successfully: topic-order-created-successfully

client:
  stock-api:
    name: stock
    url: 127.0.0.1:8086

