apiVersion: v1
kind: Service
metadata:
  labels:
    app: upspoon-order
  name: upspoon-order
spec:
  ports:
    - name: 8083-8083
      port: 8083
      protocol: TCP
      targetPort: 8083
  selector:
    app: upspoon-order
  type: ClusterIP