server:
  port: 8085

spring:
  jpa:
    database: postgresql

    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://upspoon-payment-postgresql:5432/postgres
    type: com.zaxxer.hikari.HikariDataSource

  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true

  liquibase:
    change-log: "classpath:db/changelog/master.xml"
    enabled: true
    contexts: dev

logging:
  level:
    org: info

kafka:
  address: kafka:9092
  group-id: upspoon-group-id
  topic-payment-failed: topic-payment-failed
  topic-payment-handle: topic-payment-handle
  topic-order-created-successfully: topic-order-created-successfully