server:
  port: 8085


spring:
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5435/postgres
    type: com.zaxxer.hikari.HikariDataSource
  main:
    allow-circular-references: true



logging:
  level:
    org: info

kafka:
  address: 127.0.0.1:9092
  group-id: upspoon-group-id
  topic-payment-failed: topic-payment-failed
  topic-payment-handle: topic-payment-handle
  topic-order-created-successfully: topic-order-created-successfully