apiVersion: v1
kind: Service
metadata:
  labels:
    app: upspoon-booking
  name: upspoon-booking
spec:
  ports:
    - name: 8082-8082
      port: 8082
      protocol: TCP
      targetPort: 8082
  selector:
    app: upspoon-booking
  type: ClusterIP