server:
  port: 80

spring:
  #profiles:
    #active: minikube
  kafka:
    bootstrap-servers: kafka-service:9092

  jpa:
    database: postgresql

    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sleuth:
    enabled: true
    propagation-keys: authorization

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://upspoon-authorization-user:9000

  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://upspoon-booking-postgresql:5432/postgres
    type: com.zaxxer.hikari.HikariDataSource

  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true

  liquibase:
    change-log: "classpath:db/changelog/master.xml"
    enabled: true
    contexts: dev

logging:
  level:
    org: info


kafka:
  address: kafka-service:9092
  group-id: upspoon-group-id
  topic-booking-create: topic-booking-create
  topic-booking-create-fail: topic-booking-create-fail



