server:
  port: 8082

spring:
  kafka:
    bootstrap-servers: kafka-service:9092

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create-drop

    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://upspoon-booking-postgresql:5432/postgres
    type: com.zaxxer.hikari.HikariDataSource

  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true

  liquibase:
    change-log: "classpath:db/changelog/master.xml"
    enabled: false
    contexts: dev

logging:
  level:
    org: info


kafka:
  address: kafka-service:9092
  group-id: upspoon-group-id
  topic-booking-create: topic-booking-create
  topic-booking-create-fail: topic-booking-create-fail



