apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: upspoon-authorization-user-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - host: upspoon-authorization-user.com
      http:
        paths:
          - backend:
              service:
                name: upspoon-authorization-user
                port:
                  number: 80
            path: /(.+)
            pathType: Prefix
