apiVersion: v1
kind: Service
metadata:
  labels:
    app: upspoon-authorization-user
  name: upspoon-authorization-user
spec:
  ports:
    - name: 8087-8087
      port: 8087
      protocol: TCP
      targetPort: 8087
  selector:
    app: upspoon-authorization-user
  type: ClusterIP