apiVersion: v1
kind: Service
metadata:
  labels:
    app: upspoon-order
  name: upspoon-order
spec:
  ports:
    - name: 8080-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: upspoon-order
  type: ClusterIP