apiVersion: v1
kind: Service
metadata:
  labels:
    app: upspoon-order
  name: upspoon-order
spec:
  ports:
    - name: 80-80
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: upspoon-order
  type: ClusterIP