apiVersion: skaffold/v2beta12
kind: Config
build:
  artifacts:
    - image: upspoon-payment
      jib: {}
  tagPolicy:
    sha256: {}
  local:
    push: false

deploy:
  kubectl:
    manifests: ["./deployment/*.yaml"]