# Use postgres/example user/password credentials
version: '3.8'
services:
  postgres:
    image: postgres:13.2

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432