# Use postgres/example user/password credentials
version: '3.8'
services:
  postgres-organization:
    image: postgres:13.2
    container_name: postgres-organization

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432