# Use postgres/example user/password credentials
version: '3.8'
services:
  order-postgres:
    image: postgres:13.2
    container_name: order-postgres

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5433:5433"
    command: -p 5433