server:
  port: 80

spring:
  #profiles:
    #active: aws
  main:
    allow-bean-definition-overriding: true

  sleuth:
    enabled: true
    propagation-keys: authorization

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://a10b0652697734cc0af5ec1643e74586-1635581591.us-east-1.elb.amazonaws.com

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationSorter: method
    enabled: true
    disable-swagger-default-url: true

logging:
  level:
    root: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG

client:
  authorization-api:
    name: authorization-user
    url: http://a10b0652697734cc0af5ec1643e74586-1635581591.us-east-1.elb.amazonaws.com
  order-api:
    name: order
    url: http://upspoon-order:80
  stock-api:
    name: stock
    url: http://upspoon-stock:80
  organization-api:
    name: organization
    url: http://upspoon-organization:80
  booking-api:
    name: booking
    url: http://upspoon-booking:80
  user-api:
    name: user
    url: http://upspoon-user:80