server:
  port: 80

spring:
#  profiles:
#    active: minikube
  main:
    allow-bean-definition-overriding: true

  sleuth:
    enabled: true
    propagation-keys: authorization

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://upspoon-authorization-user.com

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationSorter: method
    enabled: true
    disable-swagger-default-url: true

logging:
  level:
    root: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG

client:
  authorization-api:
    name: authorization-user
    url: http://upspoon-authorization-user.com
  order-api:
    name: order
    url: http://upspoon-order:80
  stock-api:
    name: stock
    url: http://upspoon-stock:80
  organization-api:
    name: organization
    url: http://upspoon-organization:80
  booking-api:
    name: booking
    url: http://upspoon-booking:80
  user-api:
    name: user
    url: http://upspoon-user:80