server:
  port: 8080

spring:
  main:
    allow-bean-definition-overriding: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationSorter: method
    enabled: true
    disable-swagger-default-url: true

logging:
  level:
    org: info

client:
  authorization-api:
    name: authorization-user
    url: upspoon-authorization-user
  order-api:
    name: order
    url: upspoon-order:8083
  stock-api:
    name: stock
    url: upspoon-stock:8086
  organization-api:
    name: organization
    url: upspoon-organization:8084
  booking-api:
    name: booking
    url: upspoon-booking:8082