server:
  port: 8080

spring:
  main:
    allow-bean-definition-overriding: true

  sleuth:
    enabled: true
    propagation-keys: authorization

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://upspoon-authorization-user:9000

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationSorter: method
    enabled: true
    disable-swagger-default-url: true

logging:
  level:
    root: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG

client:
  authorization-api:
    name: authorization-user
    url: upspoon-authorization-user
  order-api:
    name: order
    url: upspoon-order:8083
  stock-api:
    name: stock
    url: upspoon-stock:8086
  organization-api:
    name: organization
    url: upspoon-organization:8084
  booking-api:
    name: booking
    url: upspoon-booking:8082