server:
  port: 8080

spring:
  main:
    allow-bean-definition-overriding: true

  sleuth:
    enabled: true
    propagation-keys: authorization

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:9000
#      client:
#        registration:
#          messaging-client-oidc:
#            provider: spring
#            client-id: messaging-client
#            client-secret: secret
#            authorization-grant-type: authorization_code
#            redirect-uri: "http://127.0.0.1:8080/login/oauth2/code/{registrationId}"
#            scope: openid, profile
#            client-name: messaging-client-oidc
#          messaging-client-authorization-code:
#            provider: spring
#            client-id: messaging-client
#            client-secret: secret
#            authorization-grant-type: authorization_code
#            redirect-uri: "http://127.0.0.1:8080/authorized"
#            scope: message.read,message.write
#            client-name: messaging-client-authorization-code
#          messaging-client-client-credentials:
#            provider: spring
#            client-id: messaging-client
#            client-secret: secret
#            authorization-grant-type: client_credentials
#            scope: message.read,message.write
#            client-name: messaging-client-client-credentials
#        provider:
#          spring:
#            issuer-uri: http://localhost:9000

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationSorter: method
    enabled: true
    disable-swagger-default-url: true

logging:
  level:
    root: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG

client:
  authorization-api:
    name: authorization-user
    url: localhost:8087
  order-api:
    name: order
    url: localhost:8083
  stock-api:
    name: stock
    url: localhost:8086
  organization-api:
    name: organization
    url: localhost:8084
  booking-api:
    name: booking
    url: localhost:8082