apiVersion: v1
data:
  application.yaml: |+
    server:
      port: 8080
    
    spring:
      profiles:
        active: aws
      kafka:
        bootstrap-servers: kafka-service:9092
    
      jpa:
        database: postgresql
    
        show-sql: true
        properties:
          hibernate:
            format_sql: true
    
      datasource:
        username: postgres
        password: postgres
        url: jdbc:postgresql://upspoon-stock-postgresql:5432/postgres
        type: com.zaxxer.hikari.HikariDataSource
    
      sleuth:
        enabled: true
        propagation-keys: authorization
    
      security:
        oauth2:
          resourceserver:
            jwt:
              issuer-uri: ${APP_ISSURE_URI}
    
      main:
        allow-bean-definition-overriding: true
        allow-circular-references: true
    
      liquibase:
        change-log: "classpath:db/changelog/master.xml"
        enabled: true
        contexts: dev
    
    logging:
      level:
        org: info
    
    kafka:
      address: kafka-service:9092
      group-id: upspoon-group-id
      topic-order-create: topic-order-create
      topic-payment-failed: topic-payment-failed
      topic-payment-handle: topic-payment-handle
      topic-stock-failed: topic-stock-failed


kind: ConfigMap
metadata:
  labels:
    app: upspoon-stock-configmap
  name: upspoon-stock-configmap-app

---
apiVersion: v1
data:
  APP_ISSURE_URI: http://your-auth-server-url
  SPRING_CLOUD_KUBERNETES_CONFIG_ENABLED: "true"
  SPRING_CLOUD_KUBERNETES_CONFIG_NAME: upspoon-stock-configmap-app
  SPRING_CLOUD_KUBERNETES_SECRET_ENABLED: "true"
  SPRING_CLOUD_BOOTSTRAP_ENABLED: "true"


kind: ConfigMap
metadata:
  labels:
    app: upspoon-stock-configmap
  name: upspoon-stock-configmap-env