apiVersion: v1
kind: Service
metadata:
  labels:
    app: upspoon-stock
  name: upspoon-stock
spec:
  ports:
    - name: 80-80
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: upspoon-stock
  type: ClusterIP