server:
  port: 8084


spring:
  jpa:
    database: postgresql
    #    hibernate:
    #      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    type: com.zaxxer.hikari.HikariDataSource
  main:
    allow-circular-references: true
  liquibase:
    change-log: "classpath:db/changelog/master.xml"
    enabled: true
    contexts: dev



logging:
  level:
    org: info

kafka:
  address: 127.0.0.1:9092
  group-id: upspoon-group-id
  topic-organization-create: topic-organization-create
  topic-organization-create-fail: topic-organization-create-fail