# Use postgres/example user/password credentials
version: '3.8'
services:
  stock-postgres:
    image: postgres:13.2
    container_name: stock-postgres

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5434:5434"
    command: -p 5434