server:
  port: 8083


spring:
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5433/postgres
    type: com.zaxxer.hikari.HikariDataSource

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationSorter: method
    enabled: true
    disable-swagger-default-url: true

logging:
  level:
    org: debug

kafka:
  topic-name: topic-name