server:
  port: 8088


spring:
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    type: com.zaxxer.hikari.HikariDataSource

  sleuth:
    enabled: true
    propagation-keys: authorization

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:9000



logging:
  level:
    org: debug

kafka:
  address: 127.0.0.1:9092
  group-id: upspoon-group-id
  topic: order